# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT
---
test-free-files:
  # __init__ files for define package
  - .*__init__.py
  # File contain type aliases
  - ondivi/_internal/ondivi_types.py
  # entry.py test by integration tests
  - ondivi/entry.py
