# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT
---
version: '3'

tasks:

  docker-setup:
    cmds:
      - docker build -t ondivi-dev .

  docker-bash:
    cmds:
      - docker run -it --rm -v $(pwd):/app --name ondivi-dev ondivi-dev bash

  default:
    desc: "Build pipeline"
    deps: [install-deps,unit-tests,integration-tests,ec,lint,build]

  build:
    desc: "Build the app"
    deps: [install-deps]
    cmds:
      - poetry build

  install-deps:
    desc: "Install dependencies"
    cmds:
      - poetry install

  syntax-check:
    cmds:
    - poetry run ruff check ondivi tests --select=F --ignore=F401,F841

  type-check:
    cmds:
      - poetry run mypy ondivi tests --strict

  test:
    deps: [syntax-check,type-check]
    cmds:
      - poetry run pytest {{.CLI_ARGS}} -s -vv

  unit-tests:
    desc: "Run unit tests"
    cmds:
      - poetry run pytest tests/unit

  integration-tests:
    desc: "Run integration tests"
    cmds:
      - poetry run pytest tests/it

  fmt:
    desc: "Run formatters"
    cmds:
      - poetry run ruff check ondivi tests --fix --fix-only

  lint:
    desc: "Run linters"
    cmds:
      - poetry run ruff check ondivi tests
      - poetry run flake8 ondivi tests
      - poetry run mypy ondivi tests --strict

  cspell-baseline:
    desc: "Generate cspell baseline"
    cmds:
      - git ls-files | xargs cspell --words-only | sort -uf > cspell_custom_words.txt

  ec:
    cmds:
      - git ls-files | xargs ec

  test-repo:
    cmds:
      - poetry run python tests/helpers/define_repo.py

  clean:
    desc: "Clean caches"
    cmds:
      - git clean -f -d -x
